In [1]:
def pdrf():
    global c_pdrf
    for i, demand in enumerate(d_pdrf[0]):
        u_pdrf[d_pdrf[1][i]] += demand * np.floor(rates[0][i] * cycleIterations)
        c_pdrf += demand * np.floor(rates[0][i] * cycleIterations)
        s_pdrf[d_pdrf[1][i]] += ds_pdrf[0][i] * np.floor(rates[0][i] * cycleIterations)

In [2]:
def drf():
    global c_drf
    while(1):
        i = np.argmin(s_drf)
        if (r < d_drf[i] + c_drf).any():
            break
        else:
            u_drf[i] += d_drf[i]
            s_drf[i] += ds_drf[0][i]
            c_drf += d_drf[i]

In [3]:
def update():
    i = ds_pdrf[0].argmax()

    d_pdrf[0] = np.delete(d_pdrf[0], i, axis=0)
    d_pdrf[1] = np.delete(d_pdrf[1], i, axis=0)
    ds_pdrf[0] = np.delete(ds_pdrf[0], i, axis=0)
    ds_pdrf[1] = np.delete(ds_pdrf[1], i, axis=0)

    s_max = np.max(ds_pdrf[0]) * np.ones(len(d_pdrf[0]))
    rates = [s_max / ds_pdrf[0], np.expand_dims(np.arange(len(d_pdrf[0]),), axis=1)]

    cycleDemands = np.sum(rates[0][:,np.newaxis] * d_pdrf[0], axis=0)
    cycleIterations = np.min((r - c_pdrf) / cycleDemands)

#    print(i)
#    print(cycleDemands)
#    print(cycleIterations)

In [4]:
def check_cycles():
    global cycleDemands
    global cycleIterations
    s_max = np.max(ds_pdrf[0]) * np.ones(len(d_pdrf[0]))
    rates = [s_max / ds_pdrf[0], np.expand_dims(np.arange(len(d_pdrf[0]),), axis=1)]

    cycleDemands = np.sum(rates[0][:,np.newaxis] * d_pdrf[0], axis=0)
    cycleIterations = np.min((r - c_pdrf) / cycleDemands)

    print(cycleDemands)
    print(cycleIterations)

In [5]:
import numpy as np
import math
from numpy import random

numberOfUsers = 1000
numberOfResources = 10

r_low = 1000000
r_high = 10000001

d_low = 1
d_high = 11

r = np.random.randint(r_low, r_high, numberOfResources) #resources
c = np.zeros(numberOfResources) #consumed amounts
#d = [np.random.randint(d_low, d_high, (numberOfUsers, numberOfResources)), np.expand_dims(np.arange(10), axis=1)] #demand vector
d = np.random.randint(d_low, d_high, (numberOfUsers, numberOfResources)) #demand vector

print(d)

[[ 8  3  3 ...  3  7  4]
 [ 4  8  3 ...  7  1  9]
 [ 2  6  6 ...  4  4  2]
 ...
 [ 4  1  2 ...  8  5  7]
 [ 3  4  1 ... 10  3  2]
 [ 8  2  1 ...  9  7 10]]


In [6]:
u_drf = np.zeros((numberOfUsers, numberOfResources)) #resources allocated to users
c_drf = np.zeros(numberOfResources) #resources allocated to users
s_drf = np.zeros(numberOfUsers) #allocated dominant shares of users
ds_drf = [(d / r).max(axis=1), np.expand_dims(np.arange(10), axis=1)]
d_drf = np.copy(d)

u_pdrf = np.zeros((numberOfUsers, numberOfResources)) #resources allocated to users
c_pdrf = np.zeros(numberOfResources) #resources allocated to users
s_pdrf = np.zeros(numberOfUsers) #allocated dominant shares of users
ds_pdrf = [(d / r).max(axis=1), np.expand_dims(np.arange(numberOfUsers), axis=1)]
d_pdrf = [d, np.expand_dims(np.arange(numberOfUsers), axis=1)]

s_max = np.max(ds_pdrf[0]) * np.ones(len(d_pdrf[0]))
rates = [s_max / ds_pdrf[0], np.expand_dims(np.arange(len(d_pdrf[0]),), axis=1)]

cycleDemands = np.sum(rates[0][:,np.newaxis] * d_pdrf[0], axis=0)
cycleIterations = np.min(r / cycleDemands)

In [7]:
print(d_pdrf[0])

[[ 8  3  3 ...  3  7  4]
 [ 4  8  3 ...  7  1  9]
 [ 2  6  6 ...  4  4  2]
 ...
 [ 4  1  2 ...  8  5  7]
 [ 3  4  1 ... 10  3  2]
 [ 8  2  1 ...  9  7 10]]


In [8]:
print(r)

[11440 58399 26685 73392 14904 57319 20841 11267 36427 49946]


In [9]:
drf()

In [10]:
pdrf()
for line in (u_drf - u_pdrf) / d:
    print(line)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0

In [11]:
check_cycles()

[7187.22124381 8025.83647039 7979.15127758 7914.02093732 7792.59852836
 7930.68907126 7983.65970012 7359.70361612 7903.57635834 8010.16020729]
0.4224354895473097


In [12]:
print(np.sort((u_drf / r).max(axis=1)))

[0.00088755 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755
 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755
 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755
 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755
 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755 0.00088755
 0.00088755 0.00089938 0.00089938 0.00093935 0.00093935 0.00093935
 0.00093935 0.00093935 0.00093935 0.00093935 0.00093935 0.00093935
 0.00093935 0.00093935 0.00093935 0.00093935 0.00093935 0.00093935
 0.00093935 0.00093935 0.00093935 0.00093935 0.00093935 0.00093935
 0.00093935 0.00093935 0.00095965 0.00095965 0.00095965 0.00095965
 0.00095965 0.00095965 0.00095965 0.00095965 0.00095965 0.00095965
 0.00095965 0.00095965 0.00098828 0.00100644 0.00100644 0.00100644
 0.00100763 0.00100763 0.00100763 0.00100763 0.0010118  0.00104895
 0.00104895 0.00104895 0.00104895 0.00104895 0.00104895 0.00104895
 0.00104895 0.00104895 0.00104895 0.00104895 0.00104895 0.0010

In [13]:
print(np.sort((u_pdrf / r).max(axis=1)))

[0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.0006993
 0.0006993  0.0006993  0.0006993  0.0006993  0.0006993  0.00071004
 0.00071004 0.00071004 0.00071004 0.00071004 0.00071004 0.00071004
 0.00071004 0.00071004 0.00071004 0.00071004 0.00071004 0.00071004
 0.00071004 0.00071004 0.00071004 0.00071004 0.00071004 0.00071004
 0.000

In [14]:
for i in range(100):
    update()

In [15]:
print(len(d_pdrf[0]))

900


In [16]:
print(u_pdrf)

[[ 8.  3.  3. ...  3.  7.  4.]
 [ 8. 16.  6. ... 14.  2. 18.]
 [ 4. 12. 12. ...  8.  8.  4.]
 ...
 [ 4.  1.  2. ...  8.  5.  7.]
 [ 3.  4.  1. ... 10.  3.  2.]
 [ 8.  2.  1. ...  9.  7. 10.]]
